USE TVAPhoneTest;
-- MySQL dump 10.13  Distrib 5.5.34, for debian-linux-gnu (x86_64)
--
-- Host: ukweb001    Database: TVAPhoneManager
-- ------------------------------------------------------
-- Server version	5.5.31-0ubuntu0.12.04.1-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `clientsettings`
--

DROP TABLE IF EXISTS `clientsettings`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `clientsettings` (
  `option_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `option_owner` varchar(25) NOT NULL,
  `option_name` varchar(20) NOT NULL,
  `option_value` varchar(64) NOT NULL,
  PRIMARY KEY (`option_id`)
) ENGINE=InnoDB AUTO_INCREMENT=131 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `clientsettings`
--

LOCK TABLES `clientsettings` WRITE;
/*!40000 ALTER TABLE `clientsettings` DISABLE KEYS */;
INSERT INTO `clientsettings` VALUES 
	(1,'GLOBAL','XMPPServer','10.43.10.91'), -- IP Address or hostname of the XMPP Server (Openfire recommended) 
	(2,'GLOBAL','language','en'), -- Default language to use
	(3,'GLOBAL','country','GB'), -- Default country to use
	(4,'GLOBAL','XMPPRoom','phonebox@conference.elastix'), -- Main XMPP Chat Room, usually room_name@conference.xmpp_domain 
	(5,'GLOBAL','XMPPControlRoom','phoneboxcontrol@conference.elastix'), -- Control XMPP Chat for sending transfer etc commands 	
	(6,'GLOBAL','XMPPDomain','elastix'), -- Default XMPP Domain 
	(7,'GLOBAL','idleTimeout','120000'), -- Milliseconds before people are marked as away in XMPP Chat (2 Minutes) 
	(8,'GLOBAL','writeDBHost','10.43.5.50'), -- Host IP/Name where a client can write to a Database
	(9,'GLOBAL','writeDBUser','phonemanager'), -- User with write privileges
	(10,'GLOBAL','writeDBPass','Ph0n3m4n4g3r'), -- Password for write privileges 
	(11,'GLOBAL','writeDBDatabase','TVAPhoneManager'), -- Database name that you can write to 
	(12,'GLOBAL','incomingQueueNumber','3000'), -- Asterisk Queue to use for incoming calls 
	(13,'GLOBAL','onAirQueueNumber','3001'), -- Asterisk Queue to use to mark calls ready for on air use 
	(14,'GLOBAL','studioExtensions','5005=>Studio 1,5006=>Studio 2'), -- mapped csv list of any extensions that are studios 
	(15,'GLOBAL','queue_3001_icon','images/cross.png'), /* queue_xxxx_icon will set a default call icon on that queue to the given 
							       image */
	(16,'GLOBAL','threadPoolMax','4'), -- When doing things like DB writes how many threads we can spin up as a max 

/* Change serverHostName to the host name where the server component is running */

	(17,'serverHostName','asteriskHost','10.43.10.91'), -- IP/Host name of the Asterisk Server 
	(18,'serverHostName','asteriskUser','change me to a user name'), -- User name to use to access the Asterisk Manager Interface 
	(19,'serverHostName','asteriskPass','change me to a password'), -- Password to use to access the Asterisk Manager Interface 
	(20,'serverHostName','autoAnswerContext','custom-answerme'), -- Asterisk context to use that adds the Auto Answer headers 
	(21,'serverHostName','defaultContext','from-internal'), -- Default Asterisk context 
	(22,'serverHostName','contextMacroAuto','macro-auto-blkvm'), /* Used to ignore a lot of events generated by Asterisk with this 
									context */
	(23,'serverHostName','defaultTimeOut','30000'), -- Time out in milliseconds before assuming Asterisk command failed 
	(24,'serverHostName','channelLockTimeOut','3000'), /* Time out in milliseconds to ignore further commands sent on a channel, this 
			  				   prevents 8 people clicking answer and having the call bounce around */

/* Change sampleClientHostName to the host name where a client is running */

	(25,'sampleClientHostName','myExtension','5001'), -- Asterisk Extension that this client will use 
	(26,'sampleClientHostName','isStudio','false'), /* Prevents studio chat shortcuts and also won't mark the call red to other 
							   clients, change to true if this is a studio */
	(27,'sampleClientHostName','timezoneHourOffset','30'); /* [Optional] if you are in a timezone that is weird with +/- parts of an 
								  hour the call in progress time will start at +x minutes.  You can use 
								  this to reset that back to 0 */
	
/* The below is auto generated when a client is first loaded on a new machine it checks if an XMPP account exists for this user name
 * if not it will create one via the Openfire user creation API
	('sampleUserName','XMPPLogin','ukstudio'), -- Login name for XMPP server
	('sampleUserName','password','kbck7jj82a7i4p6lhpom0pitmn'), -- Random generated password, plain text (need to code in encryption)
	('sampleUserName','nickName','ukstudio'), --Nick name to use in XMPP chat
 */

/*!40000 ALTER TABLE `clientsettings` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `callhistory`
--

DROP TABLE IF EXISTS `callhistory`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `callhistory` (
  `callhistory_id` int(11) NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `phonenumber` varchar(16) NOT NULL,
  `state` varchar(1) NOT NULL DEFAULT 'X',
  `operator` varchar(25) NOT NULL DEFAULT 'NA',
  `callchannel` decimal(15,3) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'NA',
  `activePerson` int(11) DEFAULT NULL,
  PRIMARY KEY (`callhistory_id`),
  KEY `icallchannel` (`callchannel`)
) ENGINE=InnoDB AUTO_INCREMENT=2975 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `callinputfields`
--

DROP TABLE IF EXISTS `callinputfields`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `callinputfields` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL DEFAULT '',
  `type` varchar(24) NOT NULL DEFAULT '',
  `tooltip` varchar(64) DEFAULT NULL,
  `language` varchar(8) NOT NULL DEFAULT 'en,GB',
  `order` int(2) DEFAULT NULL,
  `parent` int(11) NOT NULL DEFAULT '1',
  `options` text,
  `mapping` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `callinputfields`
--

LOCK TABLES `callinputfields` WRITE;
/*!40000 ALTER TABLE `callinputfields` DISABLE KEYS */;
INSERT INTO `callinputfields` VALUES (1,'General','tab','','en,GB',0,-1,NULL,NULL),(2,'Personal','tab','','en,GB',1,-1,NULL,NULL),(3,'History','tab','','en,GB',2,-1,NULL,'history'),(4,'','combo','Select Call Type','en,GB',5,1,'Select Type=>none,ON AIR=>images/onair.png,OFF AIR=>images/offair.png,DVD=>images/dvd.png,Life Changed=>images/cross.png,Prayer=>images/prayer.png,Quiz=>images/quiz.png,Song=>images/song.png,Testimony=>images/testimony.png','calltype'),(5,'','textarea','Enter call information here','en,GB',6,1,NULL,'conversation'),(6,'Gender','combo','Select Gender','en,GB',7,1,'Unknown,Male,Female','gender'),(7,'Language','combo','Select Language','en,GB',8,1,'Unknown,Bengali,English,Hindi,Punjabi,Urdu','language'),(8,'Religion','combo','Select Religion','en,GB',9,1,'Unknown,Christian,Hindu,Muslim,Sikh,Other/None','religion'),(9,'Journey','combo','Select Stage of Christian Journey','en,GB',10,1,'Unknown,Christian,Interested,New Believer,Not Interested','journey'),(10,'Alert Level','combo','Select alert for this caller','en,GB',11,2,'Banned=>3,Favourite=>images/favourite.png,Normal=>0,Warning=>2','alert'),(11,'Notes','textarea','Add any extra notes to this caller','en,GB',12,2,'','notes'),(12,'Address','textarea','Add the callers postal address','en,GB',13,2,NULL,'address'),(13,'Post Code','textfield','Add the callers Post/Pin Code','en,GB',14,2,NULL,'postcode'),(14,'Email','textfield','Add the callers email address','en,GB',15,2,NULL,'email'),(15,'Location','textfield','Add the Caller\'s Location','en,GB',4,1,NULL,'location'),(16,'Name','textfield','Add the Caller\'s name','en,GB',3,1,NULL,'name'),(17,'Call Log','tab','','en,GB',16,-1,NULL,NULL);
/*!40000 ALTER TABLE `callinputfields` ENABLE KEYS */;
UNLOCK TABLES;


	

/*!40000 ALTER TABLE `clientsettings` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Table structure for table `conversations`
--

DROP TABLE IF EXISTS `conversations`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `conversations` (
  `conversations_id` int(11) NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `channel` decimal(15,3) NOT NULL DEFAULT '0.000',
  `conversation` tinytext NOT NULL,
  `person_id` int(11) NOT NULL DEFAULT '-1',
  PRIMARY KEY (`conversations_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `person`
--

DROP TABLE IF EXISTS `person`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `person` (
  `person_id` int(11) NOT NULL AUTO_INCREMENT,
  `alert` varchar(1) NOT NULL DEFAULT 'N',
  `name` varchar(64) DEFAULT NULL,
  `gender` varchar(1) NOT NULL DEFAULT 'U',
  `location` varchar(64) DEFAULT NULL,
  `address` tinytext,
  `postcode` varchar(12) DEFAULT NULL,
  `email` varchar(64) DEFAULT NULL,
  `language` varchar(64) DEFAULT NULL,
  `religion` varchar(16) DEFAULT NULL,
  `journey` varchar(16) DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci';
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Table structure for table `phonenumbers`
--

DROP TABLE IF EXISTS `phonenumbers`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `phonenumbers` (
  `numbers_id` int(11) NOT NULL AUTO_INCREMENT,
  `phone_number` varchar(16) NOT NULL,
  `person_id` int(11) NOT NULL,
  `lastUpdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`numbers_id`),
  KEY `iphone_number` (`phone_number`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=latin1 COMMENT='latin1_swedish_ci';
/*!40101 SET character_set_client = @saved_cs_client */;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2013-10-28 14:06:16
